<a href="https://colab.research.google.com/github/GandhamSRILAKSHMI1357/FMML-module-lab3/blob/main/DataScienceUsingPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Creating a NumPy Array
a. Basic ndarray
b. Array of zeros
c. Array of ones
d. Random numbers in ndarray
e. An array of your choice
f. Imatrix in NumPy
g. Evenly spaced ndarray

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Basic ndarray:", arr)

zero_array = np.zeros((3, 3))
print("Array of Zeros:\n", zero_array)

ones_array = np.ones((2, 4))
print("Array of Ones:\n", ones_array)

random_array = np.random.rand(3, 3)
print("Random Numbers in ndarray:\n", random_array)

custom_array = np.array([[10, 20, 30], [40, 50, 60]])
print("Custom Array:\n", custom_array)

identity_matrix = np.eye(4)
print("Identity Matrix:\n", identity_matrix)

even_spaced_array = np.arange(1, 20, 2)
print("Evenly Spaced ndarray:\n", even_spaced_array)

even_spaced_array2 = np.linspace(1, 10, 5)
print("Evenly Spaced ndarray with linspace:\n", even_spaced_array2)

Basic ndarray: [1 2 3 4 5]
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random Numbers in ndarray:
 [[0.24749467 0.98542365 0.0704129 ]
 [0.81502905 0.88762253 0.35941521]
 [0.15227434 0.99937552 0.82600549]]
Custom Array:
 [[10 20 30]
 [40 50 60]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Evenly Spaced ndarray:
 [ 1  3  5  7  9 11 13 15 17 19]
Evenly Spaced ndarray with linspace:
 [ 1.    3.25  5.5   7.75 10.  ]


###The Shape and Reshaping of NumPy Array
a. Dimensions of NumPy array
b. Shape of NumPy array
c. Size of NumPy array
d. Reshaping a NumPy array
e. Flattening a NumPy array
f. Transpose of a NumPy array

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("a. Number of Dimensions:", arr.ndim)
print("b. Shape of Array:", arr.shape)
print("c. Size of Array:", arr.size)

reshaped_arr = arr.reshape(3, 2)
print("d. Reshaped Array (3x2):\n", reshaped_arr)

flattened_arr = arr.flatten()
print("e. Flattened Array:", flattened_arr)

raveled_arr = arr.ravel()
print("e. Raveled Array:", raveled_arr)

transposed_arr = arr.T
print("f. Transposed Array:\n", transposed_arr)


a. Number of Dimensions: 2
b. Shape of Array: (2, 3)
c. Size of Array: 6
d. Reshaped Array (3x2):
 [[1 2]
 [3 4]
 [5 6]]
e. Flattened Array: [1 2 3 4 5 6]
e. Raveled Array: [1 2 3 4 5 6]
f. Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [3]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Using ravel()
raveled_arr = arr.ravel()
print("Raveled Array:", raveled_arr)  # Output: [1 2 3 4 5 6]

# Modifying raveled array
raveled_arr[0] = 99  # Since ravel() returns a view, the original array changes
print("Modified Original Array:\n", arr)

# Using flatten() (creates a copy)
flattened_arr = arr.flatten()
flattened_arr[1] = 88  # This will NOT affect the original array
print("Modified Flattened Array:", flattened_arr)
print("Original Array After flatten():\n", arr)

Raveled Array: [1 2 3 4 5 6]
Modified Original Array:
 [[99  2  3]
 [ 4  5  6]]
Modified Flattened Array: [99 88  3  4  5  6]
Original Array After flatten():
 [[99  2  3]
 [ 4  5  6]]


###Expanding and Squeezing a NumPy Array
a. Expanding a NumPy array
b. Squeezing a NumPy array
c. Sorting in NumPy Arrays

In [4]:
import numpy as np

arr = np.array([1, 2, 3])

col_vector = np.expand_dims(arr, axis=1)
row_vector = arr[np.newaxis, :]

arr_expanded = np.array([[[1], [2], [3]]])
squeezed_arr = np.squeeze(arr_expanded)

arr_2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_row = np.sort(arr_2d, axis=1)
sorted_col = np.sort(arr_2d, axis=0)
indices = np.argsort(arr_2d, axis=1)

print("Column Vector:\n", col_vector)
print("Row Vector:\n", row_vector)
print("Squeezed Array:", squeezed_arr)
print("Row-wise Sorted:\n", sorted_row)
print("Column-wise Sorted:\n", sorted_col)
print("Sorting Indices:\n", indices)

Column Vector:
 [[1]
 [2]
 [3]]
Row Vector:
 [[1 2 3]]
Squeezed Array: [1 2 3]
Row-wise Sorted:
 [[1 2 3]
 [4 5 6]]
Column-wise Sorted:
 [[3 1 2]
 [6 4 5]]
Sorting Indices:
 [[1 2 0]
 [1 2 0]]


###Indexing and Slicing of NumPy Array
a. Slicing 1-D NumPy arrays
b. Slicing 2-D NumPy arrays
c. Slicing 3-D NumPy arrays
d. Negative slicing of NumPy arrays

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[1:4])
print(arr[2:])
print(arr[:5])
print(arr[::2])
print(arr[-3:])
print(arr[:-2])
print(arr[::-2])

[20 30 40]
[30 40 50 60 70]
[10 20 30 40 50]
[10 30 50 70]
[50 60 70]
[10 20 30 40 50]
[70 50 30 10]


In [6]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2d[0:2, 1:3])
print(arr2d[:2, :])
print(arr2d[:, 1])
print(arr2d[::2, :])
print(arr2d[-1, :])
print(arr2d[:, -1])

[[2 3]
 [6 7]]
[[1 2 3 4]
 [5 6 7 8]]
[ 2  6 10]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 4  8 12]


In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(arr3d[:2, :, :])
print(arr3d[1, :, :])
print(arr3d[:, 0, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


###Stacking and Concatenating Numpy Arrays
a. Stacking ndarrays
b. Concatenating ndarrays
c. Broadcasting in Numpy Arrays

In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_0 = np.stack((a, b), axis=0)
stacked_1 = np.stack((a, b), axis=1)

print("Stacked along axis=0:\n", stacked_0)
print("Stacked along axis=1:\n", stacked_1)

vstacked = np.vstack((a, b))
print("Vertically Stacked:\n", vstacked)

hstacked = np.hstack((a, b))
print("Horizontally Stacked:\n", hstacked)

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

concat_axis0 = np.concatenate((x, y), axis=0)
print("Concatenation along axis=0:\n", concat_axis0)

z = np.array([[7], [8]])
concat_axis1 = np.concatenate((x, z), axis=1)
print("Concatenation along axis=1:\n", concat_axis1)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])

C = A + B
print("Broadcasted Addition:\n", C)

A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])

C = A * B
print("Broadcasted Multiplication:\n", C)

Stacked along axis=0:
 [[1 2 3]
 [4 5 6]]
Stacked along axis=1:
 [[1 4]
 [2 5]
 [3 6]]
Vertically Stacked:
 [[1 2 3]
 [4 5 6]]
Horizontally Stacked:
 [1 2 3 4 5 6]
Concatenation along axis=0:
 [[1 2]
 [3 4]
 [5 6]]
Concatenation along axis=1:
 [[1 2 7]
 [3 4 8]]
Broadcasted Addition:
 [[2 4 6]
 [5 7 9]]
Broadcasted Multiplication:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


###Perform following operations using pandas
a. Creating dataframe
b. concat()
c. Setting conditions
d. Adding a new column


In [10]:
import pandas as pd

# a. Creating a DataFrame
data1 = {'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
data2 = {'ID': [4, 5, 6], 'Name': ['David', 'Eve', 'Frank'], 'Age': [40, 45, 50]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# b. Concatenating DataFrames
df_combined = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenated DataFrame:")
print(df_combined)

# c. Setting Conditions (Filtering Data)
df_filtered = df_combined[df_combined['Age'] > 30]
print("\nFiltered DataFrame (Age > 30):")
print(df_filtered)

# d. Adding a New Column
df_combined['Category'] = ['Young' if age < 40 else 'Senior' for age in df_combined['Age']]
print("\nDataFrame with New Column:")
print(df_combined)

DataFrame 1:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

DataFrame 2:
   ID   Name  Age
0   4  David   40
1   5    Eve   45
2   6  Frank   50

Concatenated DataFrame:
   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eve   45
5   6    Frank   50

Filtered DataFrame (Age > 30):
   ID     Name  Age
2   3  Charlie   35
3   4    David   40
4   5      Eve   45
5   6    Frank   50

DataFrame with New Column:
   ID     Name  Age Category
0   1    Alice   25    Young
1   2      Bob   30    Young
2   3  Charlie   35    Young
3   4    David   40   Senior
4   5      Eve   45   Senior
5   6    Frank   50   Senior


###Perform following operations using pandas
a. Filling NaN with string
b. Sorting based on column values
c. groupby()


In [9]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', None],
    'Age': [25, 30, None, 22, 27],
    'City': ['New York', 'San Francisco', 'Chicago', 'Austin', 'New York'],
    'Salary': [70000, 80000, 65000, 72000, 75000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# (a) Filling NaN with a string
df_filled = df.fillna("Unknown")
print("\nDataFrame after filling NaN:\n", df_filled)

# (b) Sorting based on column values (Sorting by 'Age' in ascending order)
df_sorted = df.sort_values(by='Age', ascending=True)
print("\nDataFrame sorted by Age:\n", df_sorted)

# (c) Grouping by 'City' and calculating average salary
df_grouped = df.groupby('City')['Salary'].mean()
print("\nAverage Salary by City:\n", df_grouped)

Original DataFrame:
       Name   Age           City  Salary
0    Alice  25.0       New York   70000
1      Bob  30.0  San Francisco   80000
2  Charlie   NaN        Chicago   65000
3    David  22.0         Austin   72000
4     None  27.0       New York   75000

DataFrame after filling NaN:
       Name      Age           City  Salary
0    Alice     25.0       New York   70000
1      Bob     30.0  San Francisco   80000
2  Charlie  Unknown        Chicago   65000
3    David     22.0         Austin   72000
4  Unknown     27.0       New York   75000

DataFrame sorted by Age:
       Name   Age           City  Salary
3    David  22.0         Austin   72000
0    Alice  25.0       New York   70000
4     None  27.0       New York   75000
1      Bob  30.0  San Francisco   80000
2  Charlie   NaN        Chicago   65000

Average Salary by City:
 City
Austin           72000.0
Chicago          65000.0
New York         72500.0
San Francisco    80000.0
Name: Salary, dtype: float64


###Read the following file formats using pandas
a. Text files
b. CSV files
c. Excel files
d. JSON files

In [14]:
import pandas as pd

#As explained in the class, execute by creating your own data files. your own text file, json file and other file formats.
# Sample data
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

# Create a text file (tab-separated)
df_sample = pd.DataFrame(data)
df_sample.to_csv("data.txt", sep="\t", index=False)

# Create a CSV file
df_sample.to_csv("data.csv", index=False)

# Create an Excel file
df_sample.to_excel("data.xlsx", sheet_name="Sheet1", index=False)

# Create a JSON file
df_sample.to_json("data.json", orient="records", indent=4)

# Load text file
df_txt = pd.read_csv("data.txt", delimiter="\t")
print("\nText File Data:\n", df_txt)

# Load CSV file
df_csv = pd.read_csv("data.csv")
print("\nCSV File Data:\n", df_csv)

# Load Excel file
df_excel = pd.read_excel("data.xlsx", sheet_name="Sheet1")
print("\nExcel File Data:\n", df_excel)

# Load JSON file
df_json = pd.read_json("data.json")
print("\nJSON File Data:\n", df_json)


Text File Data:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

CSV File Data:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Excel File Data:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

JSON File Data:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


###Read the following file formats
a. Pickle files
b. Image files using PIL
c. Multiple files using Glob
d. Importing data from database


In [12]:
import pickle
from PIL import Image
import glob
import sqlite3

#As explained in the class create try to read a image file and display the image. Also create a query using SQL.

def read_pickle_file(file_path):
    with open(file_path, 'rb') as file:
        data = pickle.load(file)
    return data

def read_image(file_path):
    img = Image.open(file_path)
    img.show()
    return img

def read_multiple_files(folder_path, file_extension="*.txt"):
    file_paths = glob.glob(f"{folder_path}/{file_extension}")
    data = []
    for file in file_paths:
        with open(file, 'r', encoding='utf-8') as f:
            data.append(f.read())
    return data

def read_from_database(db_path, query="SELECT * FROM users"):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute(query)
    data = cursor.fetchall()
    conn.close()
    return data

# Example usage
# data = read_pickle_file('data.pkl')
# img = read_image("sample.jpg")
# text_data = read_multiple_files("my_folder")
# records = read_from_database("my_database.db")

###Demonstrate web scraping using python

In [15]:
import requests
from bs4 import BeautifulSoup

def scrape_quotes():
    # URL of the website to scrape
    url = "https://quotes.toscrape.com"

    # Send an HTTP request to fetch the webpage
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url, headers=headers)

    print(response)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.text, "html.parser")

        # Find all quote elements
        quotes = soup.find_all("span", class_="text")
        authors = soup.find_all("small", class_="author")

        # Extract and print the quotes with authors
        print("\nExtracted Quotes:\n" + "-"*50)
        for index, (quote, author) in enumerate(zip(quotes, authors), start=1):
            print(f"{index}. {quote.text} - {author.text}")
    else:
        print(f"Failed to retrieve the page. Status Code: {response.status_code}")

# Run the scraper
if __name__ == "__main__":
    scrape_quotes()

<Response [200]>

Extracted Quotes:
--------------------------------------------------
1. “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.” - Albert Einstein
2. “It is our choices, Harry, that show what we truly are, far more than our abilities.” - J.K. Rowling
3. “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.” - Albert Einstein
4. “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.” - Jane Austen
5. “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.” - Marilyn Monroe
6. “Try not to become a man of success. Rather become a man of value.” - Albert Einstein
7. “It is better to be hated for what you are than to be loved for what you are not.” - André Gide
8. “I have not failed. I've just found 10,000 ways that won't work.” - Thomas